apiVersion: v1
kind: Pod
metadata:
  name: ksbobryakov-server
  labels:
    env: test
spec:
  containers:
    - name: ksbobryakov-server
      image: ksbobryakov/server:1.0.0
      imagePullPolicy: IfNotPresent
